export const LINEAGE = [
  {
    name: "Fall '74: 12 From The Unreal",
    year: 1974,
    order: 0,
    semester: "Fall",
    members: [
      "Charles Grant",
      "George Perry",
      "Fred Lee Jones",
      "Lawrence Morton",
      "Eric Stansbury",
      "Vernon Ross",
      "Carl Bly",
      "Alois Clemons",
      "Edward Anthony",
      "Timmie Marshall",
      "Ronald Holt",
      "Ronald Grayson",
    ],
  },
  {
    name: "Spring '75: Triflin Six",
    year: 1975,
    order: 1,
    semester: "Spring",
    members: [
      "Morgan Robbins",
      "Marc Felton",
      "Edward Wheeler",
      "Allen Wright",
      "Calvin Byrd",
      "Reginald Baker",
    ],
  },
  {
    name: "Spring '76: Notorious 9",
    year: 1976,
    order: 2,
    semester: "Spring",
    members: [
      "Terrence Robinson",
      "Craig Dean",
      "William Gee",
      "Carideo Atwell",
      "James Hankerson",
      "David Thomas",
      "Dino Holley",
      "David Neville",
      "Vincent Adams",
    ],
  },
  {
    name: "Spring '77: Bits-n-Pieces",
    year: 1977,
    order: 3,
    semester: "Spring",
    members: ["Clarence Reynolds", "George Ellis"],
  },
  {
    name: "Fall '77: Bermuda Triangle",
    year: 1977,
    order: 4,
    semester: "Fall",
    members: ["Albert Grandy", "Robert Frierson", "Gregory Byron"],
  },
  {
    name: "Fall '78: One Who Dared",
    year: 1978,
    order: 5,
    semester: "Fall",
    members: ["Nate Atkins"],
  },
  {
    name: "Spring '79: Suicide Seven",
    year: 1979,
    order: 6,
    semester: "Spring",
    members: [
      "Christopher Bellfield",
      "Jerome Gardner",
      "Damon Johnston",
      "Alfred Russell",
      "Ed Davis",
      "Kenneth Bossard",
      "Michael Wiggins",
    ],
  },
  {
    name: "Spring '80: Ward 13",
    year: 1980,
    order: 7,
    semester: "Spring",
    members: [
      "Dwann Buford",
      "Derek Larker",
      "Steven Reynolds",
      "John Ellington",
      "Ross Johnson",
      "Ricardo Gray",
      "Greg Jones",
      "Francis Carson",
      "Anthony Young",
      "Preston Sampson",
      "Kenneth Andre Gladden",
      "Craig Essex",
      "Clarence Anderson",
    ],
  },
  {
    name: "Spring '81: Sabbatical Seven",
    year: 1981,
    order: 8,
    semester: "Spring",
    members: [
      "Raymond Gould",
      "Dennis Beale",
      "Raymond Bowen",
      "Jerome Dillard",
      "Lyvan Munlyn",
      "Earl Edwards",
      "Gregory Harrison",
    ],
  },
  {
    name: "Fall '83: Gap Band Five",
    year: 1983,
    order: 9,
    semester: "Fall",
    members: [
      "Anthony Gary",
      "Carlton Arrendell",
      "David Mitchell",
      "Kevan Cooper",
      "Hosea Summers",
    ],
  },
  {
    name: "Spring '85: 16 Lords Of Discipline",
    year: 1985,
    order: 10,
    semester: "Spring",
    members: [
      "Philip Hughes",
      "David Alston",
      "Craig Smith",
      "Brian Littleton",
      "Christopher Johnson",
      "Wayne Bruce",
      "Jeffrey McLean",
      "Dwight Davis",
      "Orlando Boston",
      "Thomas Alan Young",
      "Ralph Brown",
      "James Howard",
      "Rudolph Rhoades",
      "Wilbert Plummer",
      "Scott Britton",
      "Barry D. Jones",
    ],
  },
  {
    name: "Spring '86: Ten Most Wanted D.O.A.",
    year: 1986,
    order: 11,
    semester: "Spring",
    members: [
      "Bryan Barts",
      "Terence Peace",
      "Michael Hancock",
      "Terell Stafford",
      "Anthony Tyree",
      "Gregory Tolson",
      "Marc Rainey",
      "Bryan Gray",
      "Donald Giles",
      "Napoleon Saunders",
    ],
  },
  {
    name: "Spring '87: Five the Hard Way",
    year: 1987,
    order: 12,
    semester: "Spring",
    members: [
      "Richard Martin",
      "Greg Smallwood",
      "Dwayne Middleton",
      "Kevin Holmes",
      "Jonathan Byus",
    ],
  },
  {
    name: "Spring '88: The Psychotic 16",
    year: 1988,
    order: 13,
    semester: "Spring",
    members: [
      "Barry Jones",
      "Marc Minor",
      "Maurice Berry",
      "Lawrence Southall",
      "Maurice Jordan",
      "Fred McNeil",
      "Wendell Williams",
      "Edward Rosemond",
      "Reuben Atkins",
      "James Allen",
      "Jacques Walker",
      "Trevor Williams",
      "Christopher Stephens",
      "Andre Hill",
      "Rodney Bryant",
      "Mike Joseph",
    ],
  },
  {
    name: "Fall '89: The Final Four",
    year: 1989,
    order: 14,
    semester: "Fall",
    members: ["Alix Leger", "Roderick Press", "Rick Younger", "Danton Dungy"],
  },
  {
    name: "Spring '91: 8 Million Ways",
    year: 1991,
    order: 15,
    semester: "Spring",
    members: [
      "Jeremy Wagner",
      "Stanton Brown",
      "Brian Woolfolk",
      "Tarem Hendricks",
      "Wayne Vincent",
      "Christopher Lawrence",
      "Peter Johnson",
      "Hallie Williams",
    ],
  },
  {
    name: "Spring '92: Three Deep",
    year: 1992,
    order: 16,
    semester: "Spring",
    members: ["Edward Abrams", "Bruce Brown", "Malcolm Drewery"],
  },
  {
    name: "Spring '94: Body Kount 6",
    year: 1994,
    order: 17,
    semester: "Spring",
    members: [
      "Khristian Gaines",
      "Daniel Crosby",
      "Tony Sawyers",
      "Kelvin Reaves",
      "Anthony Ogbuokiri",
      "Enrique Young",
    ],
  },
  {
    name: "Spring '96: The Four Horsemen",
    year: 1996,
    order: 18,
    semester: "Spring",
    members: [
      "Charles Thomas, Jr.",
      "Claudy Jules",
      "Anthony Little",
      "Devon Jones",
    ],
  },
  {
    name: "Fall '97: Phantom Four",
    year: 1997,
    order: 19,
    semester: "Fall",
    members: [
      "Justin James",
      "Ronald E. Godsey",
      "Marc D. Barnes",
      "Bolaji Adeoye",
    ],
  },
  {
    name: "Spring '98: 6 Degrees of Separation",
    year: 1998,
    order: 20,
    semester: "Spring",
    members: [
      "Jason D. Wiles",
      "Justin W. Lee",
      "Olubunmi Akinbajo",
      "Atman A. Smith",
      "Jason E. Greenhoward",
      "Okiemute Whiteru",
    ],
  },
  {
    name: "Spring '99: 6 Disciples of Discretion",
    year: 1999,
    order: 21,
    semester: "Spring",
    members: [
      "Terron Hampton",
      "Kevin Curtain",
      "Carlos Cruz",
      "Charles Cicchetti",
      "David Williams",
      "Masud Semple",
    ],
  },
  {
    name: "Spring '00: 6 Usual Suspects",
    year: 2000,
    order: 22,
    semester: "Spring",
    members: [
      "Walter Burkhand",
      "Ray Gibbs",
      "Stewart Jazz Jones",
      "Jason Bell",
      "Nymea Morais",
      "Sean Armstrong",
    ],
  },
  {
    name: "Fall '08: Resurrection: Born Again 10",
    year: 2008,
    order: 23,
    semester: "Fall",
    members: [
      "Brandon Gardner",
      "Terrell Smith",
      "Turner Pride",
      "Kayode Ogunnaike",
      "John Nash",
      "Ricky Sessions Jr.",
      "Malcolm Ray",
      "Justin Dailey",
      "Kemar Brown",
      "Andrae Wiggins",
    ],
  },
  {
    name: "Spring '09: 2 Live Krew",
    year: 2009,
    order: 24,
    semester: "Spring",
    members: ["Branden Isaac", "Malik Waleed"],
  },
  {
    name: "Spring '10: Kaos The Trilogy",
    year: 2010,
    order: 25,
    semester: "Spring",
    members: ["Marc Bent", "Ikenna Uzomah", "Benjamin Whitfield Jr."],
  },
  {
    name: "Spring '11: Enemies of the St8",
    year: 2011,
    order: 26,
    semester: "Spring",
    members: [
      "Ermias Gherense",
      "Jeremie Lecuyer",
      "Corey Harris Jr.",
      "Julian Diolo",
      "Deonte Carter",
      "Vincent Harrington",
      "Aaron Gregg",
      "Christopher Grant",
    ],
  },
  {
    name: "Spring '12: Mission Impossible 5: Double Agents",
    year: 2012,
    order: 27,
    semester: "Spring",
    members: [
      "Trevoi Wallace",
      "Aaron Jackson",
      "Steven Lee",
      "William Stancil II",
      "Major Bottoms Jr.",
    ],
  },
  {
    name: "Spring '13: The 5yndiKate",
    year: 2013,
    order: 28,
    semester: "Spring",
    members: [
      "Robert Bailey III",
      "Nykolaus Pinnock",
      "Darien St. Jean",
      "Tyrek Cheeseboro",
      "Lyle Stewart",
    ],
  },
  {
    name: "Spring '14: The 5th Element",
    year: 2014,
    order: 29,
    semester: "Spring",
    members: [
      "Akiel Pyant",
      "Alexander Grillo",
      "Beteley Solomon",
      "Jonathan Reynolds",
      "Ivan La Rocca",
    ],
  },
  {
    name: "Fall '15: Kosa Nostra: The 13ravado",
    year: 2015,
    order: 30,
    semester: "Fall",
    members: [
      "Dominick Littleton",
      "Shelton Eley Jr.",
      "Mark Busbee",
      "Darrien Keith",
      "Brandon Chambers",
      "Darien Strachan",
      "Adam Williams",
      "Michael Pauls Jr.",
      "Cornelius Griffith",
      "Dedjrik Jeffries",
      "William Sykes III",
      "James Marrow",
      "Isaac Bagayoko",
    ],
  },
  {
    name: "Spring '17: ApoKalypse: The Survivors",
    year: 2017,
    order: 31,
    semester: "Spring",
    members: [
      "Eben Benyarku",
      "Julian Hall",
      "Nehemiah Davis",
      "Austin Jared Plummer",
      "Griffin Hall",
    ],
  },
  {
    name: "Fall '18: VindiKation: The Gallant 6",
    year: 2018,
    order: 32,
    semester: "Fall",
    members: [
      "Diran Balogun",
      "David Livingstone",
      "Isaiah Cromer",
      "Jalen Green",
      "Landen Buckson",
      "Rasheed Welsh",
    ],
  },
  {
    name: "Spring '19: PerfeKt Storm: The Prodigious 7",
    year: 2019,
    order: 33,
    semester: "Spring",
    members: [
      "Samuel Barksdale",
      "Richard Farley Mills Jr.",
      "Brendenn Davis",
      "Paul Brown-Taylor",
      "Victor Agbar",
      "Joseph Ogunbodede",
      "Tyran Hunt",
    ],
  },
  {
    name: "Spring '20: Ascension: The ProvoKative 4",
    year: 2020,
    order: 34,
    semester: "Spring",
    members: [
      "Amadou Wade",
      "Justin Pedro De Burgo",
      "Lester Crockett III",
      "Tanyi Makia Jr.",
    ],
  },
  {
    name: "Fall '21: 4 Kings of Redemption",
    year: 2021,
    order: 35,
    semester: "Fall",
    members: [
      "Adam Logan Handy",
      "Amari Samaiye",
      "Brian Ndofor",
      "Thomas Gaskins IV",
    ],
  },
  {
    name: "Spring '23: The 4saken Krusaders",
    year: 2023,
    order: 36,
    semester: "Spring",
    members: [
      "Therman Hawkins III",
      "Brandon Adams",
      "Lloyd Richards III",
      "Kylon Winston",
    ],
  },
  {
    name: "Fall '23: Kataclysm: The 4bidden Souls",
    year: 2023,
    order: 37,
    semester: "Fall",
    members: [
      "Sean William Love Smith",
      "Brown Henry Anglin IV",
      "Sebastian Decady",
      "Benjamin-Nicolas Enwesi",
    ],
  },
  {
    name: "Spring '24: Kogeki: The UnKonKerable Trinity",
    year: 2024,
    order: 38,
    semester: "Spring",
    members: ["Dylan Gabriel Thomas", "Malachi Edney-Burton", "Alex Saxton"],
  },
];
